baseURL = '/help/'
languageCode = 'en-NZ'
title = 'BTSX Help Documentation'
theme = 'hugo-book'

[params]
  BookRepo = 'https://github.com/hagenson/btsx'
  BookSearch = true
  BookComments = false
  BookToC = true
  BookSection = '/docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[menu]
  [[menu.after]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/hagenson/btsx"
    weight = 10

[permalinks]
  docs = "/:sections[1:]/:slug/"